runtime: python36
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: main.app
  secure: always
# [END handlers]

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: odia-speech-data
    SESSION_SECRET_KEY: put-a-key
#[END env]
